use std::env;
use std::fs::File;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=../codegen/vk.xml");
    println!("cargo:rerun-if-changed=../codegen/src/");
    println!("cargo:rerun-if-changed=build.rs");

    let vk_xml_path = PathBuf::from("../codegen/vk.xml");
    let vk_xml = codegen::VkXml::from(vk_xml_path).expect("parsed VkXml");

    let codegen_path =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR")).join("codegen_vk_decls.rs");
    let mut codegen_file = File::create(codegen_path).expect("codegen file");
    writeln!(codegen_file, "// Autogenerated source file.").expect("write");
    vk_xml.write_decls(&mut codegen_file).expect("write");

    let codegen_path =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR")).join("codegen_vk_defs.rs");
    let mut codegen_file = File::create(codegen_path).expect("codegen file");
    writeln!(codegen_file, "// Autogenerated source file.").expect("write");
    vk_xml.write_defs(&mut codegen_file).expect("write");
}
