[package]
name = "gpu"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
hashbrown = "0.13.2"
itertools = { workspace = true }
log = { workspace = true }
rspirv = "0.11.0"
