use std::env;
use std::fs::File;
use std::path::PathBuf;
use std::io::Write;

fn main() {
    println!("cargo:rerun-if-changed=../codegen/vk.xml");
    println!("cargo:rerun-if-changed=../codegen/src/codegen.rs");
    println!("cargo:rerun-if-changed=build.rs");

    let vk_xml_path = PathBuf::from("../codegen/vk.xml");
    let codegen_path = PathBuf::from(env::var_os("OUT_DIR").unwrap()).join("codegen.rs");

    let mut codegen_file = File::create(codegen_path).unwrap();
    writeln!(codegen_file, "// Autogenerated source file.").unwrap();

    let vk_xml = codegen::VkXml::from(vk_xml_path).unwrap();
    writeln!(codegen_file, "{}", vk_xml).unwrap();
}